#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER root
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

if [ ! -d vendor/ ]; then
    composer install
fi

if [ ! -d public/storage/ ]; then
    php artisan storage:link --force
fi

chmod -R ugo+rw /.composer
php artisan optimize:clear

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
