version: '3'
services:

    postgres:
        container_name: hidevs_postgres
        image: bitnami/postgresql:14
        ports:
            - '5432:5432'
        environment:
            POSTGRESQL_POSTGRES_PASSWORD: 'sXQHNK59FYke'
            POSTGRESQL_USERNAME: 'poostgres'
            POSTGRESQL_PASSWORD: 'poostgres'
        networks:
            tick:
                ipv4_address: 10.0.1.3
        volumes:
            - 'postgres_data:/bitnami/postgresql'
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
            retries: 3
            timeout: 5s

    redis:
        container_name: hidevs_redis
        image: bitnami/redis:7.0
        ports:
            - '6379:6379'
        environment:
            ALLOW_EMPTY_PASSWORD: 'no'
            REDIS_PASSWORD: 'sXQHNK59FYke'
            REDIS_DISABLE_COMMANDS: 'FLUSHDB,FLUSHALL'
        networks:
            tick:
                ipv4_address: 10.0.1.4
        volumes:
            - 'redis_data:/bitnami/redis/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mongodb:
        container_name: hidevs_mongodb
        image: bitnami/mongodb:5.0
        ports:
            - '27017:27017'
        environment:
            MONGODB_ENABLE_DIRECTORY_PER_DB: 'yes'
            ALLOW_EMPTY_PASSWORD: 'no'
            MONGODB_ROOT_USER: 'mongodb'
            MONGODB_ROOT_PASSWORD: 'sXQHNK59FYke'
            # MONGODB_USERNAME: 'mongodb'
            # MONGODB_PASSWORD: 'mongodb'
        volumes:
            - 'mongodb_data:/bitnami/mongodb'
        networks:
            tick:
                ipv4_address: 10.0.1.5

networks:
    tick:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.1.0/16

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
    mongodb_data:
        driver: local
